---
- hosts: all
  connection: local
  vars_prompt:
    - name: git_user_name
      prompt: What is your Git author name?
      private: no
    - name: git_user_email
      prompt: What is your Git email address?
      private: no
  tasks:
  - name: add ansible to the path
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.machine"
      create: yes
      line: export PATH="$(python -c 'import site; print(site.USER_BASE + "/bin")'):$PATH"
  - include_role:
      name: macos
  - include_role:
      name: ssh
  - include_role:
      name: homebrew
  - include_role:
      name: mas
  - include_role:
      name: tmux
  - include_role:
      name: git
    vars:
      configurations:
        - { name: user.name, value: "{{ git_user_name }}" }
        - { name: user.email, value: "{{ git_user_email }}" }
        - { name: credential.helper, value: osxkeychain }
        - { name: alias.amend, value: commit --amend }
        - { name: alias.b, value: branch }
        - { name: alias.co, value: checkout }
        - { name: alias.cob, value: checkout -b }
        - { name: alias.cp, value: cherry-pick }
        - { name: alias.r, value: remote -v }
        - { name: alias.ra, value: remote add }
        - { name: alias.rb, value: rebase -i }
        - { name: alias.smi, value: submodule init }
        - { name: alias.smu, value: submodule update }
        - { name: alias.st, value: status }
        - { name: alias.unstage, value: reset --soft HEAD^ }
        - { name: core.autocrlf, value: input }
        - { name: core.editor, value: code --wait }
        - { name: core.excludesfile, value: ~/.gitignore }
        - { name: core.whitespace, value: "-blank-at-eof,tab-in-indent" }
        - { name: help.autocorrect, value: 1 }
        - { name: mergetool.keepBackup, value: "false" }
        - { name: push.default, value: simple }
  - homebrew:
      name: "{{ item }}"
    loop:
      - ack
      - asciinema
      - base64
      - cheat
      - coreutils
      - dateutils
      - ffind
      - grc
      - grep
      - handbrake
      - jq
      - openssl
      - osxutils
      - parallel
      - rename
      - shellcheck
      - the_silver_searcher
      - vim
      - wget
  - homebrew_cask:
      name: "{{ item }}"
      accept_external_apps: yes
    loop:
      - appcleaner
      - docker
      - google-chrome
      - netspot
      - ngrok
      - onedrive
      - postman
      - sublime-text
      - vlc
  - include_role:
      name: volta
  - name: node
    shell: $HOME/.volta/volta install node
  - name: yarn
    shell: $HOME/.volta/volta install yarn
