---
- hosts: all
  connection: local
  vars_prompt:
    - name: github_username
      prompt: What is your Github username?
      private: no
  tasks:
  - include_role:
      name: multiverse
  - include_role:
      name: golang
  - include_role:
      name: volta
  - name: node
    shell: $HOME/.volta/volta fetch node
  - name: yarn
    shell: $HOME/.volta/volta install yarn
  - include_role:
      name: bazel
    vars:
      bazel_version: "0.25.3"
  - include_role:
      name: scloud
  - include_role:
      name: minikube
    vars:
      hosts:
        - 127.0.0.1 stargate-app-center.sugar.multiverse
        - 127.0.0.1 stargate-appcatalog.sugar.multiverse
        - 127.0.0.1 stargate-cloudhome.sugar.multiverse
  - include_role:
      name: homebrew
  - homebrew:
      name: "{{ item }}"
    loop:
      - awscli
      - hugo
