---
- hosts: all
  connection: local
  tasks:
  - include_role:
      name: homebrew
  - include_role:
      name: mas
  - homebrew_cask:
      name: "{{ item }}"
      accept_external_apps: yes
    loop:
      - firefox
      - google-chrome
      - postman
      - ringcentral
      - ringcentral-meetings
      - sequel-pro
