#!/usr/bin/env php
<?php

/**
 * source: https://github.com/sugarcrm/devops/wiki/Useful-Git-Hooks
 *
 * Base for this pre-commit hook is here:
 * http://webadvent.org/2008/dont-commit-that-error-by-travis-swicegood
 *
 * Changes made are the following
 *  - Ignore Known bad file in Sugar
 *  - Make sure that error_log() is not in the code
 */

$output = array();
$return = 0;
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

exec("git diff-index --cached --name-only {$against}", $output);

$filename_pattern = '/\.(php|engine|theme|install|inc|module|test|js)$/';
$exit_status = 0;

foreach ($output as $file) {
    if (!preg_match($filename_pattern, $file)) {
        continue;
    }

    if(preg_match('#sugarcrm/include/SugarObjects/templates/file/views#', $file)) {
        continue;
    }

    if (!file_exists($file)) {
        continue;
    }

    # lets parse JS files!
    if (strpos($file, '.js') !== false) {
        $cmd = "cat {$file} | grep -n \"ddescribe\|iit\" | wc -l";
        $ret = trim(exec($cmd));

        if ($ret == '0') {

            $cmd = "cat {$file} | grep -n \"debugger\" | wc -l";
            $ret = trim(exec($cmd));

            if ($ret == '0') {
                continue;
            } else {
                echo "Debugging Statements found in {$file}. Stopping Commit\n";
            }
        } else {
            echo "ddescribe or iit found in {$file}. Stopping Commit\n";
        }
    } else {
        $lint_output = array();
        exec("php -l " . escapeshellarg($file), $lint_output, $return);
        if ($return == 0) {
              $cmd = "cat {$file} | grep \"error_log(\" | wc -l";
              $ret = trim(exec($cmd));

              if ($ret == '0') {
                  continue;
              } else {
                  echo "Debugging Statement Found in {$file}!, Stopping Commit\n";
              }
        } else {
            echo implode("\n", $lint_output), "\n";
        }
    }

    $exit_status = 1;
}

exit($exit_status);
