#!/bin/bash

flavor="ent"
version="9.0.0"

usage() {
    echo "Usage:"
    echo "    rome2stack [-f] [-v]"
    exit 0
}

while getopts ":f:v:" opt; do
    case ${opt} in
    f)
        flavor=$OPTARG
        ;;
    v)
        version=$OPTARG
        ;;
    \?)
        usage
        ;;
    :)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

if [[ -z "$flavor" ]]; then
    usage
fi

if [[ -z "$version" ]]; then
    usage
fi

rome build --clean -d "$HOME/www/mango/" -f "$flavor" -v "$version" "$HOME/github.com/sugarcrm/Mango/sugarcrm"

vagrant up

echo "-
  source: $HOME/www/mango
  target: /var/www/html/dev
" >share.yaml

vagrant reload

open http://localhost:8080/dev
